<?php

if (!defined('OVERTIME_REQUEST_VERSION')) {
    define('OVERTIME_REQUEST_VERSION', '1.7.2');
}

$overtimeConfig = [
    'DEBUG' => false,

    'IBLOCK_REQUESTS' => 391,
    'IBLOCK_OVERTIME_REGISTRY' => 392,
    'IBLOCK_WORK_TYPES' => 393,
    'IBLOCK_PAYMENT_TYPES' => 394,
    'IBLOCK_STATUSES' => 388,
    'IBLOCK_DUTY_ACCESS' => 396,
    'IBLOCK_GROUP_REQUESTS' => 397,

    'WORK_TYPE_OVERTIME_ID' => 3537677,
    'WORK_TYPE_WEEKEND_ID'  => 3537684,
    'WORK_TYPE_DUTY_ID'     => 3537685,

    'STATUS_CANCELLED_ID'   => 3511775,

    // Список пользователей, которым доступен флаг "Дежурство"
    'DUTY_ACCESS_PROP_EMPLOYEE' => 'SOTRUDNIK',

    // Реестр часов сверхурочки
    'REG_PROP_EMPLOYEE' => 'SOTRUDNIK',
    'REG_PROP_YEAR'     => 'GOD',
    'REG_PROP_HOURS'    => 'KOLICHESTVO_CHASOV',

    // Типы оплаты
    'PAYMENT_PROP_WORK_TYPES' => 'TIPY_RABOTY',

    // Инфоблок 391
    'REQ_PROP_EMPLOYEE'        => 'SOTRUDNIK',
    'REQ_PROP_START'           => 'DATA_NACHALA',
    'REQ_PROP_END'             => 'DATA_OKONCHANIYA',
    'REQ_PROP_WORK_TYPE'       => 'TIP_RABOTY',
    'REQ_PROP_PAYMENT_TYPE'    => 'TIP_OPLATY',
    'REQ_PROP_STATUS'          => 'STATUS',
    'REQ_PROP_LINKED_REQUESTS' => 'SVYAZANNYE_ZAYAVKI', // PROPERTY_3107
    'REQ_PROP_HOURS'           => 'KOLICHESTVO_CHASOV',
    'REQ_PROP_JUSTIFICATION'   => 'OBOSNOVANIE',
    'REQ_PROP_JUST_FILE'       => 'OBOSNOVANIE_FAYL',
    'REQ_PROP_GROUP_LINK'      => 'GROUP_LINK',
    'REQ_PROP_WORK_START_DATE' => 'DATA_NACHALA_RABOT',
    'REQ_PROP_WORK_END_DATE'   => 'DATA_OKONCHANIYA_RABOT',
    'REQ_PROP_WORK_START_TIME' => 'VREMYA_NACHALA_RABOT',
    'REQ_PROP_WORK_END_TIME'   => 'VREMYA_OKONCHANIYA_RABOT',
    'REQ_PROP_TOTAL_HOURS'     => 'OBSHCHEE_KOLICHESTVO_CHASOV',
    'REQ_PROP_TOTAL_OT_HOURS'  => 'ITOGO_SVERKHUROCHNYKH_CHASOV',
    'REQ_PROP_TOTAL_PREMIUM_HOURS' => 'ITOGO_CHASY_DLYA_OPLATY_EDNINOVREMENOY_PRMIEY',

    // Инфоблок 397
    'GROUP_PROP_LINKED_REQUESTS' => 'SVYAZANNYE_ZAYAVKI_GRUPPY',

    'MODE_SINGLE'     => 'single',
    'MODE_MULTI_SAME' => 'multi_same',
    'MODE_MULTI_DIFF' => 'multi_diff',
];
