<?php

if (!defined('OVERTIME_REQUEST_VERSION')) {
    define('OVERTIME_REQUEST_VERSION', '1.8.4-duty-modal-fixes');
}

$overtimeConfig = [
    'DEBUG' => false,

    'IBLOCK_REQUESTS' => 391,
    'IBLOCK_OVERTIME_REGISTRY' => 392,
    'IBLOCK_WORK_TYPES' => 393,
    'IBLOCK_PAYMENT_TYPES' => 394,
    'IBLOCK_STATUSES' => 388,
    'IBLOCK_DUTY_ACCESS' => 396,
    'IBLOCK_PAST_PERIOD_ACCESS' => 401,
    'IBLOCK_GROUP_REQUESTS' => 397,
    'REQUEST_WORKFLOW_TEMPLATE_ID' => 1292,

    'WORK_TYPE_OVERTIME_ID' => 3537677,
    'WORK_TYPE_WEEKEND_ID'  => 3537684,
    'WORK_TYPE_DUTY_ID'     => 3537685,

    'STATUS_REJECTED_ID'    => 3575323,
    'STATUS_CANCELLED_ID'   => 3511775,
    'STATUS_TRANSFERRED_ID' => 3580392,
    'STATUS_REFINEMENT_ID'  => 3582614,
    'STATUS_COMPLETED_ID'   => 3511824,
    'STATUS_IN_WORK_CB_ID'  => 3578386,
    'DUTY_DUPLICATE_BLOCKING_STATUS_IDS' => [3511824, 3578386],

    // Список пользователей, которым доступен флаг "Дежурство"
    'DUTY_ACCESS_PROP_EMPLOYEE' => 'SOTRUDNIK',
    // Список сотрудников, которым разрешено создавать заявки за прошедший период
    'PAST_PERIOD_ACCESS_PROP_EMPLOYEE' => 'SOTRUDNIK',

    // Организационная структура
    'STRUCTURE_IBLOCK_ID' => 5,

    // Настройки расчетов и ограничений сверхурочной работы
    'OVERTIME_RESTRICTED_WORKDAY_START' => '09:00',
    'OVERTIME_RESTRICTED_WORKDAY_END' => '19:00',
    'OVERTIME_ANNUAL_HOURS_LIMIT' => 120.0,
    'OVERTIME_CONSECUTIVE_DAYS_LIMIT_HOURS' => 4.0,
    'OVERTIME_CONSECUTIVE_DAYS_LIMIT_DAYS' => 2,
    'OVERTIME_NIGHT_START_HOUR' => 22,
    'OVERTIME_NIGHT_END_HOUR' => 6,

    // Реестр часов сверхурочки
    'REG_PROP_EMPLOYEE' => 'SOTRUDNIK',
    'REG_PROP_YEAR'     => 'GOD',
    'REG_PROP_HOURS'    => 'KOLICHESTVO_CHASOV',

    // Типы оплаты
    'PAYMENT_PROP_WORK_TYPES' => 'TIPY_RABOTY',
    'PAYMENT_TYPE_TIME_OFF_ID' => 3537688,

    // Инфоблок 391
    'REQ_PROP_EMPLOYEE'        => 'SOTRUDNIK',
    'REQ_PROP_START'           => 'DATA_NACHALA',
    'REQ_PROP_END'             => 'DATA_OKONCHANIYA',
    'REQ_PROP_WORK_TYPE'       => 'TIP_RABOTY',
    'REQ_PROP_PAYMENT_TYPE'    => 'TIP_OPLATY',
    'REQ_PROP_STATUS'          => 'STATUS',
    'REQ_PROP_HISTORY'         => 'ISTORIYA',
    'REQ_PROP_COMMENTS'        => 'KOMMENTARII',
    'REQ_PROP_LINKED_REQUESTS' => 'SVYAZANNYE_ZAYAVKI', // PROPERTY_3107
    'REQ_PROP_HOURS'           => 'KOLICHESTVO_CHASOV',
    'REQ_PROP_JUSTIFICATION'   => 'OBOSNOVANIE',
    'REQ_PROP_ORDER_JUSTIFICATION' => 'OBOSNOVANIE_DLYA_PRIKAZA',
    'REQ_PROP_JUST_FILE'       => 'OBOSNOVANIE_FAYL',
    'REQ_PROP_GROUP_LINK'      => 'GROUP_LINK',
    'REQ_PROP_WORK_START_DATE' => 'DATA_NACHALA_RABOT',
    'REQ_PROP_WORK_END_DATE'   => 'DATA_OKONCHANIYA_RABOT',
    'REQ_PROP_WORK_START_TIME' => 'VREMYA_NACHALA_RABOT',
    'REQ_PROP_WORK_END_TIME'   => 'VREMYA_OKONCHANIYA_RABOT',
    'REQ_PROP_TOTAL_HOURS'     => 'OBSHCHEE_KOLICHESTVO_CHASOV',
    'REQ_PROP_OVERTIME_TOTAL_HOURS' => 'OBSHCHEE_KOL_VO_SVERKHUROCHNYKH_CHASOV',
    'REQ_PROP_HOURS_15'        => 'CHASY_DLYA_OPLATY_V_1_5_RAZMERE',
    'REQ_PROP_HOURS_20'        => 'CHASY_DLYA_OPLATY_V_2_RAZMERE',
    'REQ_PROP_NIGHT_HOURS_20'  => 'VKLYUCHAYA_NOCHNYE_CHASY_20',
    'REQ_PROP_TOTAL_OT_HOURS'  => 'ITOGO_SVERKHUROCHNYKH_CHASOV',
    'REQ_PROP_TOTAL_PREMIUM_HOURS' => 'ITOGO_CHASY_DLYA_OPLATY_EDNINOVREMENOY_PRMIEY',
    'REQ_PROP_SUBTYPE'         => 'PODTIP_ZAYAVKI',
    'REQ_PROP_CALCULATION_HTML'=> 'RASCHET',

    'SUBTYPE_DUTY_CB_ID'       => 3575290,
    'SUBTYPE_WEEKEND_CB_ID'    => 3575289,
    'SUBTYPE_WEEKEND_KA_ID'    => 3575289,
    'SUBTYPE_OVERTIME_CB_ID'   => 3575285,
    'SUBTYPE_OVERTIME_CB_KA_ID'=> 3575284,
    'SUBTYPE_OVERTIME_KA_ID'   => 3575288,

    // Инфоблок 397
    'GROUP_PROP_LINKED_REQUESTS' => 'SVYAZANNYE_ZAYAVKI_GRUPPY',

    'MODE_SINGLE'     => 'single',
    'MODE_MULTI_SAME' => 'multi_same',
    'MODE_MULTI_DIFF' => 'multi_diff',
];
